---
- name: checkout project
  win_command: bash {{ win_svn_co_script }} -p {{ project }} -c {{ release }} -l {{ slink }} -u {{ build_user }} -w {{ ansible_ssh_pass }}
  args:
    executable: cmd.exe
  register: checkout
- debug: var=checkout.stdout_lines

