---
- debug:
    msg: 
    - "RESULT: "
    - "Build Triggerd for {{ project }}-{{ sqaField }}{{ release }}.{{ os }}.{{ oracle }}"
    - "Build Log location: {{ log_location }}"
    - "End of triggerPlatform_builds.yaml script"
